lschaeffer313/domaine-nc-mobile

- .github/workflows/update_version.yaml
- .releaserc
> Remplacement des références à la branch master 😞 en faveur de main ❤️ 

- .github/workflows/update_version.yaml
- .releaserc
- android/app/src/main/kotlin/com/example/domaine_nc_mobile/MainActivity.kt
Ajout des issue suivantes :
- #15
> Ajout des dernières modifications

- .github/dependabot.yml
> Ajout de la config dependabot

- .github/workflows/deploy_to_play_store.yaml
- .github/workflows/update_version.yaml
- lib/page/domaine_detail_page.dart
- lib/page/search_domaine_page.dart
- lib/widget/search_bar.dart
- Séparation étapes construction artifact et déploiement dans la CI
- Changement de place de la barre de recherche
> Ajout dernières modification

- .github/workflows/deploy_to_play_store.yaml
- Correction des if dans la CI
> Ajout dernières modif

- lib/model/domaine_info.dart
- lib/page/domaine_detail_page.dart
- lib/page/search_domaine_page.dart
- lib/theme.dart
- lib/widget/custom_list_tile.dart
> Prise en compte des domaines protégés

- CONTRIBUTORS.md
A toi de jouer bro, ça devrait rendre par mal sur les téléphones
> Ajout des contributeurs

- CONTRIBUTORS.md
https://github.com/lschaeffer313/domaine-nc-mobile/issues/23#issuecomment-1328024749
> Ajout de Ronny

- CONTRIBUTORS.md
- lib/assets/constants.dart
- lib/enum/error_type.dart
- lib/page/domaine_detail_page.dart
- lib/page/search_domaine_page.dart
- lib/service/domaine_service.dart
- lib/utils/error_utils.dart
> Rajout d'un message en cas de timeout de l'API

- android/app/src/main/AndroidManifest.xml
- lib/page/domaine_detail_page.dart
- lib/service/domaine_service.dart
- pubspec.yaml
> Ajout des permission sur l'appli pour les différentes fonctionnalité

- README.md
> doc(README) : mauvais layout md

- README.md
Je crois que c'est important d'ouvir le projet.
> doc(contribuer) : section dédiée

- lib/page/domaine_detail_page.dart
> 🚨 Impossible de lire Serveur DNS dans certains cas

- CONTRIBUTORS.md
Ajout de :woman: @sverolle :rocket: :open_hands: 
cf https://github.com/lschaeffer313/domaine-nc-mobile/issues/56#issuecomment-1332739639
> doc(contributors) : Ajout de Sabrina

- .github/workflows/deploy_to_alpha.yml
- README.md
> Ajout badge sur le README

- README.md
Ajout du lient vers un super tuto dédié aux noms de domaines de Nlle Calédonie
https://sysamandine.nc/213-noms-de-domaine-nouvelle-caledonie
> doc(sysamadine) : Les noms de domaine en Nouvelle-Calédonie ?

- lib/theme/dark_theme.dart
> :bug: Icône du téléphone illisible

- lib/theme/dark_theme.dart
> Mise à jour main

- README.md
... et aussi au badge :smile_cat:
> Ajout short uri au badge

- CONTRIBUTORS.md
cf : 
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/103
> :bug:  Enlever octocat emoji

- lib/page/domaine_detail_page.dart
- lib/page/info_search_page.dart
- lib/page/search_domaine_page.dart
- lib/utils/error_utils.dart
- lib/widget/search_bar.dart
Ref : 
- #118
- #119 
- #120 
- #121
- #122 
- #123 
- #124
> 🩹 Changement effectué suite aux retour de la campagne Testeum

- .github/workflows/deploy_to_prod.yml
- pubspec.lock
- pubspec.yaml
> Mise à jour dépendance, version de dart utilisé et changement du sdk utilisé sur "Stable" pour la CI

- lib/page/domaine_detail_page.dart
- lib/widget/domain_specific_info.dart
> Changement de place du titre sur la page d'un domaine

- README.md
Il est important que les utilisateurs potentiels/prospects puissent disposer d'une ressource qui explique de manière synthétique pourquoi cette appli a été crée car...
> Ce qui intéresse les gens, c'est pas le comment... c'est "le pourquoi" ;-p "Les gens n'achètent pas ce que vous faites, ils achètent pourquoi vous le faites" - [Simon Sinek](https://youtu.be/u4ZoJKF_VuA)
:point_right: A cette fin, je mets le lien vers la [video](https://youtu.be/Ef8E69UhZ3w?t=5016) où j'explique toute l'histoire de produit
- :cinema:   [Start with why -- how great leaders inspire action | Simon Sinek](https://youtu.be/u4ZoJKF_VuA)
- :cinema:  [Mon speech (`< 15'`) à la CPS pour le  Talanoa 2022](https://youtu.be/Ef8E69UhZ3w?t=5016)
- :memo:  [Pacific Data Hub Talanoa 2002: Le pouvoir de la visualisation …
> 💡 doc(README) : (Mais...) Pourquoi cette appli :⁉️ 🤔

- CONTRIBUTORS.md
> fix(writing): Implement epicene writing in CONTRIBUTEURS.md

- README.md
https://hightest.nc/blog/gestion-des-tests/outils/temoignage-crowdtesting-ils-ont-fait-tester-leur-appli-mobile/ :heavy_heart_exclamation: :muscle:
> doc(README) : Article Testeum

- .github/workflows/deploy_to_prod.yml
- .github/workflows/on_pull_push_develop.yml
- analysis_options.yaml
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/assets/constants.dart
- lib/model/domaine_info.dart
- lib/model/domaine_search_result.dart
- lib/page/domaine_detail_page.dart
- lib/routes/search_route.dart
- lib/service/domaine_service.dart
- pubspec.lock
> Ajout lint pour le code dart

- CONTRIBUTORS.md
cf 
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/113
> doc(README) : AJout contributeur designer du logo cool

- README.md
cf 
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/22
> :memo:  doc(README) : lien post fastlane

- lib/page/domaine_detail_page.dart
> 178 bug accorder pluriel sur serveurs dns

- lib/page/domaine_detail_page.dart
> :bug: Accorde au pluriel serveur en fonction du nombre de serveur

- README.md
cf : 
[HigTest blog post ](https://www.linkedin.com/posts/hightest_7-ans-d%C3%A9j%C3%A0-que-nous-partageons-sur-ce-blog-activity-7158187126235242496-71wN?utm_source=share&utm_medium=member_desktop)this morning:
> doc(blog) : Add english testeum blog post

- CONTRIBUTORS.md
[Mélanie GAULT](https://github.com/MelanieGault) assure le dev et la maintenance de l'API Gateway sur APIGEE et nous a permis de basculer sur Google APIGEE, et assure le support
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/198
- https://github.com/lschaeffer313/domaine-nc-mobile/pull/199
- [🔑 APIGEE 101: onboarding & authentication](https://dev.to/optnc/apigee-101-onboarding-authentication-1ghl)
Le but de cette PR est de documeter cela et de célébrer cette toute nouvelle version de l'appli mobile :hugs:
> :clap:  doc: Ajout de Mélanie GAULT aux contributeurs
